### ISSUE TITLE
Dont log connect information to stdout

### ISSUE THREAD

**Issue by ColdHeat** [therootcompany/sclient#1]
Hi there, thanks for writing sclient! It's providing the base functionality in our [snicat](https://github.com/CTFd/snicat) tool. 

Would it be possible to stop outputting the connection info information by default? 

https://github.com/therootcompany/sclient/blob/455db509286f2ae69bddb0e3139f9b344fb54a0a/sclient.go#L153-L154

Perhaps add a verbose argument or something like that?

**Comment by coolaj86** [comment]
I'd accept a PR for something like that.

I'd prefer a `-q` or `--silent` over a `-v` or `--debug` - since the primary use case of the tool is for development and debugging.
